### ISSUE TITLE
Caching and reformatting 

### ISSUE THREAD

**Issue by ambientlight** [mapzen/tileserver#86]
Thanks a lot for providing a tilezen stack. Love it. 
I am curious about one thing: are you guys actually using this `tileserver(master)` code as it is in production? 

I noticed that mapzen returns `.mvt` tiles quite fast. However when I run `tileserver` as it is with caching enabled, the cached `.mvt` will return pretty slow especially for mid-zoom levels that are largest in size. I looked into the code and found that `reformat_from_stored_json` will be called even I have `.mvt` tiles available in cache. Once modified to read without reformat it returns instantly as expected.

My question is - what is reformatting used for and why it is needed on each non-json tile request?

**Comment by nvkelso** [comment]
Hi @ambientlight, thanks for checking out Tilezen and tileserver :) Generally speaking yes tileserver like you see it is used in prod, but off the latest tagged release [v1.4.0](https://github.com/tilezen/tileserver/releases/tag/v1.4.0), which is very close to master but master has a few more dev commits in it today since the release 20 days ago.

We pre-cache many tiles for Mapzen's production setup, and actually use tilequeue to most of that initial generation. Tileserver remains on the hot path in production, though, for requests where the tile is not yet in cache. 

The behavior with `reformat_from_stored_json` sounds weird here in tileserver. @rmarianski can you comment on that, please?

**Comment by ambientlight** [comment]
@nvkelso Thanks! So you mean you are serving cached tiles statically on something like CloudFront-backed s3 buckets? And then if there are no such static tiles available -> you would then route it to tileserver to compute? This would that explain the difference in behavior.

**Comment by nvkelso** [comment]
Yes. We write out to S3 and then have Fastly at the edge. If Fastly doesn’t
see the tile on S3, it routes the request to tileserver.

**Comment by ambientlight** [comment]
Got it, thanks a lot!

**Comment by rmarianski** [comment]
> The behavior with reformat_from_stored_json sounds weird here in tileserver. @rmarianski can you comment on that, please?

Logic that's no longer relevant. Should get cleaned up.

**Comment by rmarianski** [comment]
This just got cleaned up in master in https://github.com/tilezen/tileserver/pull/94.
