### ISSUE TITLE
Writing to cache/store after generation

### ISSUE THREAD

**Issue by tomass** [mapzen/tileserver#87]
Thank you for the great software!

Do I understand correctly, that at this time it is not possible to write vtile generated by tileserver on demand to cache/store. So that if the same request from the client comes in after some time, same tile would not have to be generated again.

Looks like currently cache/store is only filled by running tilequeue script and generating specified tiles (and it is hard to know which tiles would be requested, very low percentage of high zoom level tiles are ever requested so there is no point to generate them all and it takes a lot of time). Tiles not found in cache/store and generated on demand by tileserver are thrown away?

Thank you

**Comment by iandees** [comment]
I took out the store code in #85 because Mapzen is trying to optimize its tile response time (by doing more work in tilequeue and relying less on tileserver).

We probably should have kept it in there and configured it to be off on our servers. I'll look at doing that next week, but for now if you want to take a look at that pull request to see what was taken out you can see how we implemented storing tiles in tileserver.

**Comment by rmarianski** [comment]
Like @iandees mentioned, We're planning on adding some kind of caching back in ourselves. Sounds like we might want to think about growing an abstraction for this, or maybe use the same `store` interface that exists but grow a redis implementation for it.

**Comment by nvkelso** [comment]
@tomass In the meantime, I suggest using the tagged production release instead: https://github.com/tilezen/tileserver/releases/tag/v1.4.0.

**Comment by tomass** [comment]
Thank you a lot for information and suggestions! It was really helpful!
